name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello @${{github.actor}}, <br> Thank you for opening an issue. :partying_face: <br> To get assigned to this particular issue please use <b>/assign</b><br>'
          pr-message: "<h1> :partying_face: Congratulations :tada: </h1> <h3> :pray: Thank you @${{github.actor}} for taking out your time and contributing to our project. Make sure that you have followed the guidelines and filled the PR Template properly. We will soon review this and if everything looks good it will be merged. Happy Contributing!</h3>"
